services:
  web:
    image: nginx:alpine
    container_name: validator-web
    working_dir: /application
    depends_on:
      - php-fpm
    volumes:
      - ./public:/application/public
      - ./storage:/application/storage
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_LOCAL_PORT}:80

  php-fpm:
    build:
      context: ./docker
      dockerfile: ./php82.dockerfile
      target: base_php
      args:
        PHP_XDEBUG_ENABLE: ${PHP_XDEBUG_ENABLE:-0}
        PHP_XDEBUG_PORT: ${PHP_XDEBUG_PORT:-9011}
    environment:
      PHP_IDE_CONFIG: serverName=${PHP_XDEBUG_SERVER:-xdebug}
    working_dir: /application
    user: 1000:1000
    depends_on:
      - db
    volumes:
      - ./:/application
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres
    container_name: validator-db
    environment:
      PGUSER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${POSTGRESS_LOCAL_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
